dist: bionic
language: go

go:
  - 1.13.x
  - master
  - tip

os:
  - linux
  - osx

install: true

notifications:
  email: false

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -v -race