dist: bionic
language: go

go:
  - 1.13.x
  - master
  - tip

os:
  - linux
  - osx

matrix:
  # It's ok to fail on unstable development versions of Go.
  allow_failures:
    - go: tip
  # Don't wait for tip tests to finish.
  # Mark the test run green if the tests pass on the stable versions.
  fast_finish: true

install: true

notifications:
  email: false

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -v -race